var Ism= prompt("Ismingiz !");
console.log("Ismingiz !: " + Ism);
var Familyasi= prompt("Familiyangiz!");
console.log("Familiyangiz: " + Familyasi);
var OtasningIsmi= prompt("Otangizning ismi !");
console.log("Otangizning ismi !: " + OtasningIsmi);
var OmasningIsmi= prompt("Onangizning ismi!");
console.log("Onangizning ismi !: " + OmasningIsmi);
var OiladagiFarxandlarSoni= prompt("Oiladagi Farzandlar Soni");
console.log("Oiladagi Farzandlar Soni !: " + OiladagiFarxandlarSoni);
var IshYOJoyi= prompt("Ish yoki(O'qish joyingiz !)");
console.log("Ish yoki(O'qish joyingiz !): " + IshYOJoyi);
var Hobbiysi= prompt("Hobbiyingiz !");
console.log("Hobbiyingiz !: " + Hobbiysi);
var TuglganSanasi= prompt("Tugilgan Sanagiz!");
console.log("Tugilgan  !: " +TuglganSanasi );
var TugilganJoui= prompt("Tug'ilgan Joyingiz!");
console.log("Tug'ilgan Joyingiz !: " + TugilganJoui);
var Millati= prompt("Millatingiz !");
console.log("Millatingiz !: " + Millati );
var TelRaqami= prompt("Telifon Raqamingiz !");
console.log("Telifon Raqamingiz !: " + Ism);
var E_Poctasi= prompt("E-mail!");
console.log("E-mail!: " + E_Poctasi);
